-- FILE: alx_book_store.sql

-- 1. Create the database if it doesn't already exist
IF DB_ID(N'ALX_BOOK_STORE') IS NULL
BEGIN
    CREATE DATABASE ALX_BOOK_STORE;
END;
GO

-- 2. Use the newly created database
USE ALX_BOOK_STORE;
GO

-- 3. Create the Authors table
IF OBJECT_ID(N'dbo.AUTHORS','U') IS NULL
BEGIN
    CREATE TABLE dbo.AUTHORS (
        AUTHOR_ID INT PRIMARY KEY,
        AUTHOR_NAME VARCHAR(215) NOT NULL
    );
END;

-- 4. Create the Books table
IF OBJECT_ID(N'dbo.BOOKS','U') IS NULL
BEGIN
    CREATE TABLE dbo.BOOKS (
        BOOK_ID INT PRIMARY KEY,
        TITLE VARCHAR(130) NOT NULL,
        AUTHOR_ID INT NOT NULL,
        PRICE DECIMAL(10, 2) NOT NULL, -- Changed DOUBLE to DECIMAL for currency
        PUBLICATION_DATE DATE,
        CONSTRAINT FK_BOOKS_AUTHORS FOREIGN KEY (AUTHOR_ID) REFERENCES dbo.AUTHORS(AUTHOR_ID)
    );
END;

-- 5. Create the Customers table
IF OBJECT_ID(N'dbo.CUSTOMERS','U') IS NULL
BEGIN
    CREATE TABLE dbo.CUSTOMERS (
        CUSTOMER_ID INT PRIMARY KEY,
        CUSTOMER_NAME VARCHAR(215) NOT NULL,
        EMAIL VARCHAR(215) NOT NULL UNIQUE,
        ADDRESS VARCHAR(MAX)
    );
END;

-- 6. Create the Orders table
IF OBJECT_ID(N'dbo.ORDERS','U') IS NULL
BEGIN
    CREATE TABLE dbo.ORDERS (
        ORDER_ID INT PRIMARY KEY,
        CUSTOMER_ID INT NOT NULL,
        ORDER_DATE DATE NOT NULL,
        CONSTRAINT FK_ORDERS_CUSTOMERS FOREIGN KEY (CUSTOMER_ID) REFERENCES dbo.CUSTOMERS(CUSTOMER_ID)
    );
END;

-- 7. Create the Order_Details table (often named OrderDetails or OrderItems)
IF OBJECT_ID(N'dbo.ORDER_DETAILS','U') IS NULL
BEGIN
    CREATE TABLE dbo.ORDER_DETAILS (
        ORDERDETAILID INT PRIMARY KEY,
        ORDER_ID INT NOT NULL,
        BOOK_ID INT NOT NULL,
        QUANTITY INT NOT NULL, -- Changed DOUBLE to INT since quantity is typically an integer
        CONSTRAINT FK_ORDERDETAILS_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES dbo.ORDERS(ORDER_ID),
        CONSTRAINT FK_ORDERDETAILS_BOOKS FOREIGN KEY (BOOK_ID) REFERENCES dbo.BOOKS(BOOK_ID)
    );
END;